mode: MPIIFaceGaze
device: cuda
dataset:
  dataset_dir: datasets/MPIIFaceGaze.h5
transform:
  mpiifacegaze_face_size: 224
  mpiifacegaze_gray: False
model:
  name: mobilenet_v2
test:
  test_id: 0
  checkpoint: experiments/mpiifacegaze/mobilenetv2/exp00/00/checkpoint_0010.pth
  output_dir: experiments/mpiifacegaze/mobilenetv2/exp00/00/eval
  batch_size: 256
  dataloader:
    num_workers: 2
    pin_memory: False
cudnn:
  benchmark: True
  deterministic: False
