mode: MPIIGaze
device: cuda
dataset:
  dataset_dir: datasets/MPIIGaze.h5
model:
  name: resnet_preact
test:
  test_id: -1
  checkpoint: experiments/mpiigaze/resnet_preact/exp00/all/checkpoint_0050.pth
  output_dir: experiments/mpiigaze/resnet_preact/exp00/all/eval
  batch_size: 256
  dataloader:
    num_workers: 4
    pin_memory: False
cudnn:
  benchmark: True
  deterministic: False
